### ISSUE TITLE
Making a future request and letting callback work with result - some are missing

### ISSUE THREAD

**Issue by hermanTenuki** [ross/requests-futures#109]
Hi, i have following pseudo-code with futures:

```python
def _future_request_callback(future: Future, *args, **kwargs):
	"""Function that has to be called after future's request finished"""
	response = future.result()
	# some work with result

def make_future_request(data: dict):
	"""Function that makes future request and attaching callback to it"""
	future = FuturesSession().post('https://example.com', data=data)
	future.add_done_callback(_future_request_callback)

class SomeAPIView(APIView):
	def get(request, *args, **kwargs):
		"""Django API View which is called when client is calling the url"""
		data = {}
		# some work with data

		# create future request and don't ever wait for it manually
		make_future_request(data)  

		return Response()
```

It should on every user request to Django-APIView, send future request and let another thread to work with result in callback function.

**The problem is that sometimes callback is not called and even request itself is not being sent to the destination url.**

I think maybe that is happening because of future object is being created inside `make_future_request` function, and it is immediately getting out of scope means that garbage collector can kill it and clean it with all related objects to it at it's own will. I am not experienced with threads and want you to guide me if i'm using module wrong and my assumption is true or not.

**Comment by ross** [comment]
> I think maybe that is happening because of future object is being created inside `make_future_request` function, and it is immediately getting out of scope means that garbage collector

That is likely accurate, thought there's others a couple layers to what's going on. 

### Problems with the callback 

The `request` is passed to the callback rather than the future. With the type on the parameter there I'm guessing an exception is thrown in the background worker thread when the callback is invoked.

```python
def _future_request_callback(future: Future, *args, **kwargs):
	"""Function that has to be called after future's request finished"""
	response = future.result()
	# some work with result
```

Based on what it appears you're trying to do here you're looking for a "fire-and-forget" behavior where the request is sent off, but the response is ignored/never retrieved. That should be possible with requests-futures, but it's not exactly what it's intended for and thus it'll be doing some extra work behind the scenes for no reason. You don't need the callback so it can just be removed.

### FuturesSession lifetime

From the looks of it a new `FuturesSession` is being created on each request. That would result in a lot of extra overhead and also is likely the actual problem with scope. The session is the object that owns the worker pool and when it goes out of scope there's likely nothing to pick up the job and make the request in the first place. It'll be a race condition to which happens first.

You probably want the session object to live on the class, something like:

```python
class SomeAPIView(APIView):
        session = FuturesSession()

	def get(self, request, *args, **kwargs):
		"""Django API View which is called when client is calling the url"""
		data = {}
		# some work with data

		# create future request and don't ever wait for it manually
		self.session.post('https://example.com', data=data)

		return Response()
```

That should queue up the request for the shared FuturesSession and allow it to be sent off in the background on that long-lived session.

**Comment by hermanTenuki** [comment]
Thanks, that helped, though i kept a callback.
Also for anyone who might read this in future while working with django and futures - don't forget to turn on threading in uwsgi with `--enable-threads`.

Btw, might be good to somehow mention this garbage collection thing with scopes in README, thanks again and peace :)
