### ISSUE TITLE
add ProcessPoolExecutor to background_callback

### ISSUE THREAD

**Issue by mancioshell** [ross/requests-futures#11]
Hi. requests supports from 2.1.0 pickleable of Response objects. So maybe we could work to make background_callback available to work with ProcessPoolExecutor.
I'm newbie python developer, but i would contribute to do it.

Best regards,
Alessandro.

**Comment by asfaltboy** [comment]
## Rant
Hello guys, personally would find it **very useful** to opt for a `ProcessPoolExecutor`. I have a project where I'm executing many requests that return very big JSON responses.

In my use case, the way memory allocation in python works makes those big JSON strings eat up a huge amount of system memory, which does not get released to OS even if I periodically `shutdown` the `executor` and force garbage collection. Using processes here would make the solution trivial since we would cycle processes instead of threads, releasing memory when each process finishes.

## Solution for pickling
It seems `session.request` "pickles" just fine today, and as for the `callback` function, it seems using `functools.partial` would do the trick. The only requirement for pickling the "partial" `callback`, is to make it an importable (i.e top level) function. Here is a working POC: https://gist.github.com/asfaltboy/ba33885f7fe08012d79b

P.s: will submit a PR, once I've added the tests.
