### ISSUE TITLE
Provide background_callback_kwargs?

### ISSUE THREAD

**Issue by guettli** [ross/requests-futures#53]
I don't like closures very much. I know I could use them here to solve this issue. ...

Why not add background_callback_kwargs to pass kwargs to the background_callback?

**Comment by ross** [comment]
Mostly just wasn't the designed for us-case. The behavior matches the way requests itself works http://docs.python-requests.org/en/master/user/advanced/#event-hooks

That really provides more functionality & flexibility anyway. If I had it to do over I wouldn't have added the support for the `background_callback` at all as that really just duplicates the functionality of requests itself in a less flexible manner (not sure if it didn't exist when i wrote the lib or if I just didn't find it/know about it.)

I'd generally suggest using the stuff build in to requests rather than `background_callback`. I'll likely be looking to remove it altogether then next time I get around to spending some time on the library.

**Comment by guettli** [comment]
Thank you for the explanation. Yes, this issue should be closed.
