### ISSUE TITLE
Using concurrent.futures map with requests-futures

### ISSUE THREAD

**Issue by jlevers** [ross/requests-futures#75]
Is there any way to use the `map` functionality of `concurrent.futures` with `requests-futures`? I'm trying to do something like this, which is of course not working because `requests-futures` doesn't implement `map`:
```python
tpe = ThreadPoolExecutor(max_workers=self.workers)
with FuturesSession(executor=tpe) as executor:
      result = executor.map(self.process_line, self.get_line())
```
Is there a workaround for this? Thanks!

**Comment by ross** [comment]
The name `executor` makes me think there's a misunderstanding of what the `FuturesSession` does. It's not a child/implementation of the `Executor` class, but instead it's a drop-in replacement for `requests.Session`.  It wouldn't really make sense for it to implement `map` or any of the other executor type stuff itself. It instead allows you to make sync `requests` calls without changing any params/usage. They just return a futures object and thus are async. Rather than implement a `.map` function, it could just be called in a `map()`, e.g.

```python
#!/usr/bin/env python

from concurrent.futures import as_completed
from pprint import pprint
from requests_futures.sessions import FuturesSession

with FuturesSession(max_workers=2) as session:

    def make_request(url):
        return session.get(url)

    urls = ['http://httpbin.org/get?i={:04d}'.format(i) for i in range(10)]
    # This will map urls to futures objects that are async requests for
    # those url
    futures = map(make_request, urls)

    # This will map the futures objects to their responses as they complete in
    # whatever order they complete. There's really not much advantage to the
    # as_completed here since they're all being converted before things move
    # on, but I think it's closer conceptually to what you were wanting to do
    # with the map.
    #responses = map(lambda f: f.result(), as_completed(futures))
    # Do something with the responses here

    # This way would let you actually take advantage of things being async and
    # start processing responses as quickly as possible as soon as they're done
    # while others are still queued or in flight.
    for future in as_completed(futures):
        response = future.result()
        pprint({
            'response': response,
            'request': response.request,
            'url': response.request.url,
        })
```


Which when run looks like:

```
(env)MacBook-Pro:tmp ross$ ./map.py
{'request': <PreparedRequest [GET]>,
 'response': <Response [200]>,
 'url': 'http://httpbin.org/get?i=0000'}
{'request': <PreparedRequest [GET]>,
 'response': <Response [200]>,
 'url': 'http://httpbin.org/get?i=0001'}
{'request': <PreparedRequest [GET]>,
 'response': <Response [200]>,
 'url': 'http://httpbin.org/get?i=0003'}
{'request': <PreparedRequest [GET]>,
 'response': <Response [200]>,
 'url': 'http://httpbin.org/get?i=0002'}
{'request': <PreparedRequest [GET]>,
 'response': <Response [200]>,
 'url': 'http://httpbin.org/get?i=0004'}
{'request': <PreparedRequest [GET]>,
 'response': <Response [200]>,
 'url': 'http://httpbin.org/get?i=0005'}
{'request': <PreparedRequest [GET]>,
 'response': <Response [200]>,
 'url': 'http://httpbin.org/get?i=0006'}
{'request': <PreparedRequest [GET]>,
 'response': <Response [200]>,
 'url': 'http://httpbin.org/get?i=0007'}
{'request': <PreparedRequest [GET]>,
 'response': <Response [200]>,
 'url': 'http://httpbin.org/get?i=0008'}
{'request': <PreparedRequest [GET]>,
 'response': <Response [200]>,
 'url': 'http://httpbin.org/get?i=0009'}
```

**Comment by jlevers** [comment]
Ah, my bad, sorry for the misunderstanding. What I'm trying to do is iterate over a large CSV (~3M lines) of URLs, download the image at each URL, and then record each image that is downloaded in a separate CSV. I was running into [this issue](https://github.com/requests/requests/pull/399) in `requests`, and was hoping to get around it using `requests-futures`, but I misunderstood the relationship between the two packages. Thanks for the clarification!

**Comment by ross** [comment]
`requests-futures` is pretty good at that sort of thing so long as the image files sizes aren't huge (since they'll be buffered in memory.) The code snippet above is just about what you'd need, the urls could come from the CSV and the files could be written out in the body of the for loop. If you wanted to you could likely do the writing in the background using [hooks](https://github.com/ross/requests-futures#working-in-the-background) and just check on the status of things and write the output CSV in the for loop.

**Comment by jlevers** [comment]
Yeah, I agree that `requests-futures` would be good for the problem I'm trying to solve, except that with the issue I linked to in my last comment, I'm unable to use `requests` for more than a few hundred thousand images at a time (at the most) without hitting that error―and I believe I'd have the same problem using `requests-futures`, since it's implemented with `requests`. That being said, if I can figure out a way around that error, I'll definitely use `requests-futures` to speed things up.
