### ISSUE TITLE
Can hooks be awaited?

### ISSUE THREAD

**Issue by TAbdiukov** [ross/requests-futures#88]
Can hooks be awaited?

I'm trying to write the saving routine for my parser, but I still cant comprehend `requests-futures
`. I wonder, is it possible to have response-responding hooks so that they would save output async? Whatever my async hook is being called, I get `(myhook) was never awaited`

Cheers

**Comment by ross** [comment]
There are hooks in the underlying requests library for request complete that you could add in and save the response content in the worker rather than the main loop. If you're rather seperate the workers doing the writing from those doing the requests you'd need to set up your own threads/worker pool to take the responses once they finish. `as_completed` can be useful for that. I haven't messed with requests futures and await, but that's not the way I'd go about it.
