### ISSUE TITLE
FuturesSession does not "cancel" outstanding requests

### ISSUE THREAD

**Issue by grantjenks** [ross/requests-futures#99]
From the README:
```
In this example, the second or third request will be skipped, saving time and resources that would otherwise be wasted.
```
So I tried it with:
```
import time

from requests_futures.sessions import FuturesSession

start_time = time.time()

with FuturesSession(max_workers=1) as session:
    future = session.get('https://httpbin.org/get')
    future2 = session.get('https://httpbin.org/delay/10')
    future3 = session.get('https://httpbin.org/delay/10')
    response = future.result()

end_time = time.time()
print(f'Duration: {end_time - start_time:.3f}')
```
And it prints:
```
$ ipython ~/scratch.txt
Duration: 20.890
```
Doesn't seem that anything was skipped? I thought it would finish in less than a second.

**Comment by ross** [comment]
Yeah, just tested this with both py2 and py3 and get the same result. I'm fairly sure that wasn't the case when things were originally written up/doc'd, but it's many 🌔s ago...

If you ctrl-c things while it's spinning it looks like the executor's shutdown method is waiting for all the threads.

```
(env) salmon:py3 ross$ ~/tmp/cancel.py
^CTraceback (most recent call last):
  File "/Users/ross/tmp/cancel.py", line 12, in <module>
    future3 = session.get('https://httpbin.org/delay/4')
  File "/private/tmp/py3/env/lib/python3.8/site-packages/requests/sessions.py", line 421, in __exit__
    self.close()
  File "/private/tmp/py3/env/lib/python3.8/site-packages/requests_futures/sessions.py", line 110, in close
    self.executor.shutdown()
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 236, in shutdown
    t.join()
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

https://github.com/python/cpython/blob/b580ed1d9d55461d8dde027411b90be26cae131e/Lib/concurrent/futures/thread.py#L228-L229

That's being called from FuturesSession.close https://github.com/ross/requests-futures/blob/f6203f62d31b8aa45fe5d770cfff657480aed186/requests_futures/sessions.py#L107-L110 since the session object "owns" the executor. It doesn't pass `wait=False` so gets the default of true. Tbh I'm not sure without thinking about it really deeply whether it should, but it would see less surprising, but still may leak some things/work when you'd otherwise think they'd finished. I'm not sure if there's a way to kill/stop the in progress work and that seems even more dangerous/edge casey anyway.

Short term if you want to avoid the behavior I'd recommend passing in your own ThreadPoolExecutor. With one provided the shutdown method won't be called by requests_futures and things should come back immediately, though work may still be going on in the background.

Will leave this open to track the problem and see if there's a clean/full solution, but it'll likely be a while before I get a chance to look into it.

**Comment by edenraf** [comment]
I believe this is still an issue. I am implementing FuturesSession and at the end of the with loop it takes forever to continue to further code:

```
with sessions.FuturesSession(max_workers=workers_num) as session:
    #some fast operations here

"""
A VERY LARGE DELAY (about 60 seconds)
"""
with concurrent.futures.ThreadPoolExecutor() as e:
    #some fast operations here
```
Still looking for a workaround to get rid of this delay...any ideas?

**Comment by grantjenks** [comment]
To cancel open requests in the thread pool then the underlying socket will need to have shutdown() and close() called on it: https://stackoverflow.com/questions/64434461/how-to-abort-cancel-http-request-in-python-thread the current requests api doesn’t expose this functionality and the requests-futures library doesn’t currently do anything to cancel open requests. In the thread pool executor api, the future can only be canceled before it’s started. Once started,  the cancel method becomes a no-op because Python threads cannot be canceled.
